[package]
name = "bitcoin_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = { version = "0.26.0", features = ["all-keys", "electrum"] }
bitcoin = { version = "0.29.2", features = ["std"] }
electrum-client = "0.16.0"
rand = "0.8"
hex = "0.4"